### ISSUE TITLE
Lambda between AWS IoT core and SiteWise

### ISSUE THREAD

**Issue by samverma05** [aws-quickstart/quickstart-aws-industrial-machine-connectivity#7]
Hello Team,

My team currently have a complete setup of AWS IoT, the existing infrastructure includes Ignition connectivity as well with Iot core. 
Looking for help, my team just want to install Sitewise and the related lambda function to get data from Ignition. are there any steps or guidelines to do iot core and sitewise connectivity to have end to end integration (Igntion -> Iot core -> Sitewise)?

**Comment by nsstensoriot** [comment]
Currently there's no support in the Quickstart for that. All of the Ignition -> SItewise telemetry data pipeline is over OPC-UA, which currently happens via the [Greengrass IoT Sitewise Connector](https://docs.aws.amazon.com/greengrass/latest/developerguide/iot-sitewise-connector.html).

That being said, you could comment out the parts of the Cloudformation template dealing with EC2/Kinesis/etc that aren't related to the core Asset Model Converter pipeline. Then you'd just need to utilize the [Asset Model Converter](https://github.com/aws-quickstart/quickstart-aws-industrial-machine-connectivity/tree/master/functions/source/AssetModelConverter) to ingest the asset/asset models structure into IoT Sitewise. The Asset Model Converter uses S3 as the source of any assets/models structure inputs, and DynamoDB as a normalized state store for handling change-sets to that structure.

From there you'd want to follow the documentation on [Ingesting data to AWS IoT SiteWise from AWS IoT things ](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/ingest-data-from-iot-things.html), being sure to pay attention to setting the correct 'property alias' to match your Ignition setup.

**Comment by roshrimal** [comment]
@nsstensoriot i have gone through the  **Ingesting data to AWS IoT SiteWise from AWS IoT things** documentation and found that we need to create model in sitewise first and then the data will flow from iot core to sitewise. i am curious to know ...
is it possible to create sitewise model by iot core rule only ? 
in other words would it be possible to flow data from iot core to sitewise without creating anything in sitewise ?
(asking it because the rule creation allows to proceed even when we wont select any sitewise model in "By asset ID and property ID"  option.)

Thanks

**Comment by nsstensoriot** [comment]
I'm not aware of any method to do that directly from IoT Core via a rule. You'd have to create IoT Sitewise AssetsModels/Assets before you can ingest data into IoT Sitewise.

**Comment by roshrimal** [comment]
> 
> 
> I'm not aware of any method to do that directly from IoT Core via a rule. You'd have to create IoT Sitewise AssetsModels/Assets before you can ingest data into IoT Sitewise.

Thanks for the quick response .

**Comment by barmangaurav** [comment]
@nsstensoriot Hi, Could you please comment on below approach, We created IMC stack using dataflow option 2a (IoT core to IoT Sitewise) successfully, post that if we publish message to topics in this order -> NBIRTH then DBIRTH then DDATA, will the **node and asset be auto created in Sitewise** leveraging AssetModelIngestionLambda & AssetModelConverterLambda (I could see cloud watch logs that these two lambdas are triggered with my messages) but no node or asset being created at Sitewise end??

Also, after creating IMC stack, is there manual set up needed? As per your above comment, post utilizing asset model converter, From there you'd want to follow the documentation on Ingesting data to AWS IoT SiteWise from AWS IoT things being sure to pay attention to setting the correct 'property alias' to match your Ignition setup.

**Comment by nsstensoriot** [comment]
@barmangaurav It sounds like you may not have completed the 'Post Deployment Steps' listed in the user guide. That should take care of finishing up the Ignition setup so that certificates are accepted, and connectivity between Ignition and IoT Sitewise is completed. This should also trigger a NBIRTH/DBIRTH series of messages that will trigger the AssetModelConverter to create assets/asset models in Sitewise.

**Comment by barmangaurav** [comment]
> 
> 
> @barmangaurav It sounds like you may not have completed the 'Post Deployment Steps' listed in the user guide. That should take care of finishing up the Ignition setup so that certificates are accepted, and connectivity between Ignition and IoT Sitewise is completed. This should also trigger a NBIRTH/DBIRTH series of messages that will trigger the AssetModelConverter to create assets/asset models in Sitewise.

@nsstensoriot Thank you so much, I will finish post deployment steps and check for the final status.

**Comment by sshvans** [comment]
Resolved in #11
