### ISSUE TITLE
Cloud Formation Script Failing - Attribute: PublicIp was not found for resource: i-01f6f7d55fbb20284

### ISSUE THREAD

**Issue by navilwayne** [aws-quickstart/quickstart-aws-industrial-machine-connectivity#9]
Hi Folk

I am trying to create IMC Kit sep up via CFScript, but while i am entering my public (My IP from the browser) in AWS console template, template creation is failing & getting error : **Attribute: PublicIp was not found for resource: i-01f6f7d55fbb20284**

Referred Document :
**	User Public IP Address: Input your public IP address in the format “x.x.x.x” so the EC2 instance security groups allow access from your IP address.**

Template Name : IMC-VirtualSetUp26July-Workload-PZMUACT6CEFE-Virtual-TUTPISIP4F48

Thanks
Navil

**Comment by nsstensoriot** [comment]
What deployment type did you go for, and what did you use for inputs into the template? Which template did you use? Exact answers might be helpful so we can be of assistance. We'll try to recreate this on our end.

**Comment by samverma05** [comment]
we used option 2a.

**Comment by nsstensoriot** [comment]
I've just gone through and tested Option 2a using an existing default VPC, couldn't reproduce the issue.

The only thing that comes to mind here, is that the 'PublicIp' attribute mentioned above in the error is actually the public ip address of an EC2 instance that's been deployed in the stack. If it was deployed into an existing VPC, using a subnet that had 'Auto-assign public IPv4 address' set to 'No', then the EC2 instance wouldn't have a public ip address.

This would explain the error you got.

**Comment by navilwayne** [comment]
We have tried with Option 2a, you said you used existing VPC, but we are creating everything from scratch, in CFScript we are passing the
Template S3 URL: https://aws-quickstart.s3.amazonaws.com/quickstart-aws-industrial-machine-connectivity/templates/IMC-master.template.yaml. 
Attached Template Image for your reference & public IP we passed after checking in the browser MY IP.
![IMC_ISSUE](https://user-images.githubusercontent.com/11074957/88885209-b5100300-d255-11ea-9690-dc0e1557e2f4.JPG)

**Comment by navilwayne** [comment]
@nsstensoriot  can u plz tell us in the yaml file where exactly we have to change the existing VPC endpoint & we can give a try !
![IMC_ISSUE_VPC](https://user-images.githubusercontent.com/11074957/88913695-18625b00-d27f-11ea-8d09-5c96ce4102f8.JPG)

**Comment by nsstensoriot** [comment]
Hrm, I just tested using the [master template](https://aws-quickstart.s3.amazonaws.com/quickstart-aws-industrial-machine-connectivity/templates/IMC-master.template.yaml), and it worked fine for me. Made sure to match the settings you used.

Another thing to consider, is that the quickstart will deploy multiple nested stacks. I'm wondering if one of the other stacks failed, causing the original error you had. The root cause could be something in one of the nested stacks that didn't deploy properly.

That said, if you want to deploy using an existing VPC, you'd use the [Workload Template](https://aws-quickstart.s3.amazonaws.com/quickstart-aws-industrial-machine-connectivity/templates/IMC-workload.template.yaml) as opposed to the master template. You'll have to specify IDs in relation to the existing VPC and subnet to deploy into. Feel free to give it a try.

**Comment by navilwayne** [comment]
Hi @nsstensoriot  we tried with the Workload Template & pass the existing vpc id , but still same error : 

2020-08-05 15:23:34 UTC+0530 | IMC-VirtualSetUp05Aug-Virtual-**DBG9XN55A1ZB** | CREATE_FAILED | Attribute: PublicIp was not found for resource: i-07451edXXXXXXXf
-- | -- | -- | --

Please let us know the fix !

**Comment by nsstensoriot** [comment]
Just as an update, this is still on our radar but we've been unable to replicate it still on our end. Investigations are continuing. The only thing that stands about above is the PublicSubnet1CIDR being 0.0.0.0/0. That doesn't seem correct?

Other than that, still looking into it.

**Comment by nsstensoriot** [comment]
@navilwayne After the meeting we had, did you have any further questions or issues related to this?

**Comment by navilwayne** [comment]
Thanks @nsstensoriot , resolved now !
